name: Breaking Recaps
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Breaking Recaps
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#757575'
    - '#fbfbff'
    - '#0b4f6c'
    - '#20bf55'
    - '#a9a6b0'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
